CAI/CAI.Web/Controllers/ActivationKeyController.cs
namespace CAI.Web.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using Common.CustomExceptions;
    using Services.Abstraction;
    using Services.Models.ActivationKey;
    using Services.Models.Intention;

    public class ActivationKeyController : Controller
    {
        private readonly IActivationKeyService _activationKeyService;

        public ActivationKeyController(IActivationKeyService activationKeyService)
        {
            this._activationKeyService = activationKeyService;
        }

        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var key = this._activationKeyService.FindKey(id.Value);

                return View(key);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var key = this._activationKeyService.FindKey(id.Value);

                return View(key);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,IntentionId")] ActivationKeyViewModel keyModel)
        {
            try
            {
                var key = this._activationKeyService.FindKey(keyModel.Id);

                if (this.ModelState.IsValid)
                {
                    if (this._activationKeyService.EditKey(keyModel, this.User.Identity.Name))
                    {
                        return RedirectToAction("Details", "Intention", new { id = key.IntentionId });
                    }
                }

                return View(key);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Create(long intentionId)
        {
            return View(new ActivationKeyCreateModel { IntentionId = intentionId });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,IntentionId")] ActivationKeyCreateModel model)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    var id = this._activationKeyService.RegisterKey(model, this.User.Identity.Name);

                    //return RedirectToAction("Details", new { id = id });
                    return RedirectToAction("Details", "Intention", new { id = model.IntentionId });
                }

                return View(model);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            try
            {
                if (id == null || id < 1)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var key = this._activationKeyService.FindKey(id.Value);

                return View(key);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                var key = this._activationKeyService.FindKey(id);

                if (!this._activationKeyService.DeleteKey(id, this.User.Identity.Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
                }

                return RedirectToAction("Details", "Intention", new { id = key.IntentionId });
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
    }
}

CAI/CAI.Web/Controllers/IntentionRecognitionController.cs
namespace CAI.Web.Controllers
{
    using Data.Filtering;
    using Services.Abstraction;
    using System.Data.Entity;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Common.CustomExceptions;
    using Common.Enums;
    using Microsoft.AspNet.Identity;
    using Models.IntentionRecognition;
    using Services.Models.Bot;

    public class IntentionRecognitionController : Controller
    {
        private readonly IIntentionRecognitionService _intentionRecognitionService;
        private readonly IBotService _botService;

        public IntentionRecognitionController(IBotService botService,
            IIntentionRecognitionService intentionRecognitionService)
        {
            this._intentionRecognitionService = intentionRecognitionService;
            this._botService = botService;
        }

        [Authorize]
        public ActionResult Index()
        {
            var filter = new BotFilter() { IsDeleted = false, UserId = this.User.Identity.GetUserId() };
            var data = this._botService.GetAllBotsByFilter(filter);

            return View(data);
        }

        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image")] BotCreateModel bot)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    bot.BotType = BotType.IntentionRecognizer;
                    bot.EnvironmentType = EnvironmentType.Production;
                    bot.UserId = this.User.Identity.GetUserId();
                    this._intentionRecognitionService.RegisterNewIntentionRecognitionBot(bot, this.User.Identity.Name);

                    return RedirectToAction("Index");
                }

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image")] BotViewModel bot)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    this._botService.EditBot(bot, this.User.Identity.Name);

                    return RedirectToAction("Index");
                }

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        public ActionResult TrainBot(long botId)
        {
            try
            {
                this._intentionRecognitionService.TrainIntentionRecognitionBot(botId);

                this.ViewBag.Message = "Training done";

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                if (!this._botService.DeleteBot(id, this.User.Identity.Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
                }

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        public ActionResult Chat(long? botId)
        {
            if (botId == null || botId < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(botId.Value);

                if (bot == null)
                {
                    return HttpNotFound();
                }

                return View(new ChatViewModel { Bot = bot });
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._intentionRecognitionService.Dispose();
                this._botService.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

CAI/CAI.Web/Controllers/TrainingDataController.cs
namespace CAI.Web.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using Common.CustomExceptions;
    using Services.Abstraction;
    using Services.Models.Intention;
    using Services.Models.TrainingData;

    public class TrainingDataController : Controller
    {
        private readonly ITrainingDataService _trainingDataService;

        public TrainingDataController(ITrainingDataService trainingDataService)
        {
            this._trainingDataService = trainingDataService;
        }

        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var data = this._trainingDataService.Find(id.Value);

                return View(data);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var data = this._trainingDataService.Find(id.Value);

                return View(data);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,IntentionId")] TrainingDataViewModel dataModel)
        {
            try
            {
                var data = this._trainingDataService.Find(dataModel.Id);

                if (this.ModelState.IsValid)
                {
                    if (this._trainingDataService.Edit(dataModel, this.User.Identity.Name))
                    {
                        return RedirectToAction("Details", "Intention", new { id = data.IntentionId });
                    }
                }

                return View(data);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Create(long intentionId)
        {
            return View(new TrainingDataCreateModel() { IntentionId = intentionId });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,IntentionId")] TrainingDataCreateModel dataModel)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    var id = this._trainingDataService.Register(dataModel, this.User.Identity.Name);

                    return RedirectToAction("Details", "Intention", new { id = dataModel.IntentionId });
                    //return RedirectToAction("Details", new {id = id});
                }

                return View(dataModel);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var data = this._trainingDataService.Find(id.Value);

                return View(data);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                var data = this._trainingDataService.Find(id);

                if (!this._trainingDataService.Delete(id, this.User.Identity.Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
                }

                return RedirectToAction("Details", "Intention", new { id = data.IntentionId });
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
    }
}

CAI/CAI.Web/Views/Intention/Create.cshtml
@model CAI.Services.Models.Intention.IntentionCreateModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*@{ Model.BotId = ViewBag.Message; }
    @Html.HiddenFor(m => m.BotId);*@
    <div class="form-horizontal">
        <h4>Intention</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Details", "IntentionRecognition", new { id = @Model.BotId }, null)
</div>

CAI/CAI.Web/Views/Intention/Delete.cshtml
@model CAI.Services.Models.Intention.IntentionViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Intention</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", new { id = Model.Id })
        </div>
    }
</div>

CAI/CAI.Web/Views/Intention/Details.cshtml
@model CAI.Services.Models.Intention.IntentionViewModel

<div>
    <h4>Intention</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
    
    <p>
        @Html.ActionLink("Create New", "Create", "ActivationKey", new { intentionId = @Model.Id }, null)
    </p>
    <label for="keysTable">@Html.DisplayNameFor(model => model.ActivationKeys)</label>
    <div id="keysTable">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ActivationKeys.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ActivationKeys.FirstOrDefault().CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ActivationKeys.FirstOrDefault().ModifiedOn)
                </th>
                <th></th>
            </tr>

            @foreach (var key in Model.ActivationKeys)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => key.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => key.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => key.ModifiedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "ActivationKey", new { id = key.Id }, null) |
                        @Html.ActionLink("Details", "Details", "ActivationKey", new {id = key.Id}, null) |
                        @Html.ActionLink("Delete", "Delete", "ActivationKey", new {id = key.Id}, null)
                    </td>
                </tr>
            }
        </table>
    </div>
    
    <p>
        @Html.ActionLink("Create New", "Create", "TrainingData", new { intentionId = @Model.Id }, null)
    </p>
    <label for="keysTable">@Html.DisplayNameFor(model => model.TrainingData)</label>
    <div id="keysTable">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TrainingData.FirstOrDefault().Content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TrainingData.FirstOrDefault().CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TrainingData.FirstOrDefault().ModifiedOn)
                </th>
                <th></th>
            </tr>

            @foreach (var key in Model.TrainingData)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => key.Content)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => key.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => key.ModifiedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "TrainingData", new { id = key.Id }, null) |
                        @Html.ActionLink("Details", "Details", "TrainingData", new { id = key.Id }, null) |
                        @Html.ActionLink("Delete", "Delete", "TrainingData", new { id = key.Id }, null)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index", "IntentionRecognition", null, null)
</p>

CAI/CAI.Web/Views/Intention/Edit.cshtml
@model CAI.Services.Models.Intention.IntentionViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Intention</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Details", "IntentionRecognition", new { id = Model.BotId }, null)
</div>