CAI/CAI.Web/Models/IntentionRecognition/ChatViewModel.cs
namespace CAI.Web.Models.IntentionRecognition
{
    using Services.Models.Bot;

    public class ChatViewModel
    {
        public BotViewModel Bot { get; set; }
    }
}

CAI/CAI.Web/Controllers/IntentionController.cs
namespace CAI.Web.Controllers
{
    using System;
    using System.Net;
    using System.Web.Mvc;
    using Common.CustomExceptions;
    using Common.Enums;
    using Services.Abstraction;
    using Services.Models.Bot;
    using Services.Models.Intention;

    public class IntentionController : Controller
    {
        private readonly IIntentionService _intentionService;

        public IntentionController(IIntentionService intentionService)
        {
            this._intentionService = intentionService;
        }

        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var intention = this._intentionService.FindIntention(id.Value);

                return View(intention);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var intention = this._intentionService.FindIntention(id.Value);

                if (intention == null)
                {
                    return HttpNotFound();
                }

                return View(intention);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] IntentionViewModel intentionModel)
        {
            try
            {
                var intention = this._intentionService.FindIntention(intentionModel.Id);

                if (this.ModelState.IsValid)
                {
                    if (this._intentionService.EditIntention(intentionModel, this.User.Identity.Name))
                    {
                        return RedirectToAction("Details", "IntentionRecognition", new { id = intention.BotId });
                    }
                }

                return View(intention);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Create(long botId)
        {
            return View(new IntentionCreateModel { BotId = botId });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,BotId")] IntentionCreateModel intention)
        {
            if (this.ModelState.IsValid)
            {
                var id = this._intentionService.RegisterIntention(intention, this.User.Identity.Name);

                return RedirectToAction("Details", new { id = id });
            }

            return View(intention);
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var intention = this._intentionService.FindIntention(id.Value);
                return View(intention);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                var intention = this._intentionService.FindIntention(id);

                if (!this._intentionService.DeleteIntention(id, this.User.Identity.Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
                }

                return RedirectToAction("Details", "IntentionRecognition", new { id = intention.BotId });
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._intentionService.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

CAI/CAI.Web/Controllers/IntentionRecognitionController.cs
namespace CAI.Web.Controllers
{
    using Data.Filtering;
    using Services.Abstraction;
    using System.Data.Entity;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Common.CustomExceptions;
    using Common.Enums;
    using Microsoft.AspNet.Identity;
    using Models.IntentionRecognition;
    using Services.Models.Bot;

    public class IntentionRecognitionController : Controller
    {
        private readonly IIntentionRecognitionService _intentionRecognitionService;
        private readonly IBotService _botService;

        public IntentionRecognitionController(IBotService botService,
            IIntentionRecognitionService intentionRecognitionService)
        {
            this._intentionRecognitionService = intentionRecognitionService;
            this._botService = botService;
        }

        [Authorize]
        public ActionResult Index()
        {
            var filter = new BotFilter() { IsDeleted = false, UserId = this.User.Identity.GetUserId() };
            var data = this._botService.GetAllBotsByFilter(filter);

            return View(data);
        }

        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image")] BotCreateModel bot)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    bot.BotType = BotType.IntentionRecognizer;
                    bot.EnvironmentType = EnvironmentType.Production;
                    bot.UserId = this.User.Identity.GetUserId();
                    this._intentionRecognitionService.RegisterNewIntentionRecognitionBot(bot, this.User.Identity.Name);

                    return RedirectToAction("Index");
                }

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image")] BotViewModel bot)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    this._botService.EditBot(bot, this.User.Identity.Name);

                    return RedirectToAction("Index");
                }

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null || id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(id.Value);

                return View(bot);
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        public ActionResult TrainBot(long botId)
        {
            try
            {
                this._intentionRecognitionService.TrainIntentionRecognitionBot(botId);

                this.ViewBag.Message = "Training done";

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                if (!this._botService.DeleteBot(id, this.User.Identity.Name))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
                }

                return RedirectToAction("Index");
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        public ActionResult Chat(long? botId)
        {
            if (botId == null || botId < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var bot = this._botService.FindBot(botId.Value);

                if (bot == null)
                {
                    return HttpNotFound();
                }

                return View(new ChatViewModel { Bot = bot });
            }
            catch (NotFoundException ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._intentionRecognitionService.Dispose();
                this._botService.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

CAI/CAI.Web/Views/IntentionRecognition/Chat.cshtml
@model CAI.Web.Models.IntentionRecognition.ChatViewModel

@{
    ViewBag.Title = "Intention Recognition";
}

@*<h2>title</h2>
    <h3>@ViewBag.Message</h3>*@

@*<div id="msgs">

    </div>*@

<div class="jumbotron">
    <div class="container text-center row">
        <h2 class="label label-default" style="font-size: 25px">Bot: @Model.Bot.Name</h2>
        <br />
        <h2 class="label label-default" style="font-size: 25px">Type: @Model.Bot.BotType</h2>
    </div>
</div>

<ul id="msgs" class="list-group"></ul>

<div>
    @*<input id="minput" type="text" />*@
    <div class="input-group">
        <span class="input-group-addon">Input</span>
        <input id="input-msg" type="text" class="form-control" name="msg" placeholder="Enter text">
    </div>
    <button type="button" class="btn-success btn-lg" id="send">Send</button>
</div>

@section scripts {
    @Scripts.Render("~/bundles/signalr")
    <script src="/signalr/hubs"></script>

    <script>
        $(function () {
            $.connection.hub.start();

            var chat = $.connection.intentionRecognitionHub;
            chat.client.receiveMessage = (botMsg) => {

                for (var i = 0; i < botMsg.length; i++) {
                    $('#msgs').append('<li class="list-group-item list-group-item-success">Bot: ' + botMsg[i] + '</li>');
                }
                //for (var line in botMsg) {
                //    $('#msgs').append('<li class="list-group-item list-group-item-success">Bot: ' + line + '</li>');
                //}
                //$('#msgs').append('<li class="list-group-item list-group-item-success">Bot: ' + botMsg + '</li>');
                console.log(botMsg);
            }

            $('#send').click(() => {
                var userMsg = $('#input-msg').val();
                $('#msgs').append('<li class="list-group-item list-group-item-warning">You: ' + userMsg + '</li>');
                console.log(userMsg);

                chat.server.sendMessege(@Model.Bot.Id, userMsg);
            });
        })
    </script>
}

CAI/CAI.Web/Views/IntentionRecognition/Create.cshtml
@model CAI.Data.Models.Bot

@*@{
    Layout = null;
}*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BotType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BotType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BotType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnvironmentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnvironmentType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnvironmentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeletedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeletedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeletedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeletedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeletedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeletedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CAI/CAI.Web/Views/IntentionRecognition/Delete.cshtml
@model CAI.Services.Models.Bot.BotViewModel
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BotType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BotType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnvironmentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnvironmentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CAI/CAI.Web/Views/IntentionRecognition/Details.cshtml
@model CAI.Services.Models.Bot.BotViewModel

<div>
    <br/>
    <h3>Bot Details</h3>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BotType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BotType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnvironmentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnvironmentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>

    @*@Html.DropDownList("element", Model.Intentions.Select(x => new SelectListItem(){ Text = x.Name}))*@
    
    <p>
        @Html.ActionLink("Create New", "Create", "Intention", new { botId = @Model.Id }, null)
    </p>
    <label for="intentionsTable">@Html.DisplayNameFor(model => model.Intentions)</label>
    <div id="intentionsTable">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Intentions.FirstOrDefault().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Intentions.FirstOrDefault().CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Intentions.FirstOrDefault().ModifiedOn)
                </th>
                <th></th>
            </tr>

            @foreach (var intention in Model.Intentions)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => intention.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => intention.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => intention.ModifiedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Intention", new { id = intention.Id }, null) |
                        @Html.ActionLink("Details", "Details", "Intention", new {id = intention.Id}, null) |
                        @Html.ActionLink("Delete", "Delete", "Intention", new {id = intention.Id}, null)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

CAI/CAI.Web/Views/IntentionRecognition/Edit.cshtml
@model CAI.Services.Models.Bot.BotViewModel
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CAI/CAI.Web/Views/IntentionRecognition/Index.cshtml
@model IEnumerable<CAI.Services.Models.Bot.BotViewModel>

<h3>@ViewBag.Message</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BotType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BotType)
            </td>
            <td>
                @{
                    if (!string.IsNullOrEmpty(item.Image))
                    {
                        <img src=@item.Image style="height: 100px; display: block; margin: 0 auto;">
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedOn)
            </td>
            <td>
                @Html.ActionLink("Train", "TrainBot", new { botId = item.Id }) |
                @Html.ActionLink("Use Bot", "Chat", new { botId = item.Id }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>